### ISSUE TITLE
Tracking Issue for Mod Installation

### ISSUE THREAD

**Issue by Windows10CE** [thunderstore-io/thunderstore-cli#57]
Tracking issue for TCLI's mod installation capabilities

All of this is on the [develop branch](https://github.com/thunderstore-io/thunderstore-cli/tree/develop) until further notice for quick iteration

Currently, this is the checklist of things needed to make this even remotely workable as a shipped product:

- [x] A reorganization of the Options/Configs structure, expects a thunderstore.toml file to always be present (done with f7012ee728e3d8ebbd0375fbb2b075597846adef and b484ed86e39ca65eb1da4878083bd254734a11dd)
- [x] Location for profiles/configs, currently `%APPDATA%/ThunderstoreCLI/` on Windows (I believe) and `~/.config/ThunderstoreCLI/` on Linux
- [x] General structure for game/profile configuration (https://github.com/thunderstore-io/thunderstore-cli/blob/develop/ThunderstoreCLI/Game/GameDefinition.cs and https://github.com/thunderstore-io/thunderstore-cli/blob/develop/ThunderstoreCLI/Game/ModProfile.cs)
- [x] "Mod manager" interface contract (https://github.com/thunderstore-io/thunderstore-cli/blob/develop/ThunderstoreCLI/Game/ModManager.cs)
- [ ] `install` subcommand interface and implementation
- [ ] Example mod manager implementation for BepInEx
- [ ] Mod installation from repository (will most likely require manifest v1 to be workable with current structure, otherwise will need rewrites, therefore https://github.com/thunderstore-io/Thunderstore/issues/93 is blocking here) 
    - [ ] Automatic game recognition, ideally would use a new Thunderstore API instead of being hardcoded like r2mm/tmm 
- [ ] Plugin system for additional mod managers, see #58 
- [ ] `run` subcommand interface and implementation
