### ISSUE TITLE
Tracking Issue for TCLI Plugins

### ISSUE THREAD

**Issue by Windows10CE** [thunderstore-io/thunderstore-cli#58]
TCLI should be extremely extensible in order to allow communities to expand and utilize it to their needs, and so that if needed, a community can add whatever functionality is needed without having to resort to PRing TCLI itself.

Some of the things that allow for extension:

- [ ] Mod managers, which allow for custom install/run logic for different loaders
- [ ] Subcommands, which would allow new/niche functionality to be added without feature creep on the core functionality
- [ ] Package build logic? Unsure if this would allow for anything more than what pre/post build events would allow
- [ ] Possibly just include C# modding libraries like MonoMod/HarmonyX in addition to the other methods? This would allow for basically everything, but I'm unsure if that should be "officially supported" or not, since this could lead to "I was relying on that internal functionality!" hell

Other than that basic functionality, I haven't really decided at all how these should be implemented/what they should be required to provide, so I'm very much open to suggestion here
